version: '3.9'

services:
  opencode:
    image: dehemart/opencode:latest
    container_name: opencode
    volumes:
      - "./theme:/usr/app"
    command: bash -c "
      opencode configure ${API_KEY} ${PASSWORD} ${THEME_ID} &&
      opencode download &&
      opencode clean &&
      opencode watch"
